name: invernadero
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.15.1
  flutter_launcher_icons: ^0.14.4
  google_sign_in: ^6.2.1
  fl_chart: ^0.66.0
  firebase_database: ^10.5.6
  google_fonts: ^6.0.0
  share_plus: ^10.0.0
  flutter_native_splash: ^2.4.6
  app_links: ^6.4.1
  shared_preferences: ^2.3.1
  pdf: ^3.11.0
  printing: ^5.12.0
  intl: ^0.18.1
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Logoapp.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/Splashscreen.jpg
    - assets/logo.png
    - assets/Invernadero.png
    - assets/lechuga.png
    - assets/jitomate.png
    - assets/pepino.jpg
    - assets/Cebra.jpg
    - assets/Fitonia.jpg
    - assets/Incienso.jpg
    - assets/GestionInv.jpg
    - assets/fresa.jpg
    - assets/pepino.jpg
    - assets/pimiento.jpg
    - assets/tomate.jpg

flutter_native_splash:
  color: "#A5D6A7" # Fondo verde claro
  image: assets/Invernadero.png
  android_12:
    color: "#A5D6A7"
    image: assets/Invernadero.png
